name: status_based_state
description: "A lightweight Flutter package for managing UI states using a status-based approach."
version: 1.0.0
repository: https://github.com/altaysakarya/status_based_state

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: